src/core/src/engine.rs
Argument list updated for engine creation method.
Updated new wrapper type.
=> Updating argument list in Engine for start in Engine.rs

.gitattributes
=> Enforce EOL to LF in git repo

src/core/src/engine.rs, src/core/src/service.rs
Complete fork resolution logic. Clean up code
to ready for compilation. Comment out for some
incomplete dependencies.
Part implement block sanity check.
=> Complete fork resolution logic

src/core/src/engine.rs, src/core/src/service.rs
Add k-test to sanity check with validator registry interaction
stubbed. Also add get_setting(key) method in service.rs as
wrappers over actual get_setting(block_id, vec[key]).
=> Add k-test to sanity checks

poet2-engine.dockerfile
=> Remove extra commands from dockerfile

src/core/src/enclave_sim.rs, src/core/src/engine.rs, src/core/src/service.rs
Create certificate and seek wait_time from certificate.
Integrate it into engine event handling. Update
enclave_sim where ever needed.
=> Integrate enclave_sim into core

src/core/src/consensus_state_store.rs, src/core/src/database/config.rs, src/core/src/database/database.rs, src/core/src/database/lmdb.rs, src/core/src/database/mod.rs
=> Basic consensus state store impl

src/core/src/validator_registry_proto.rs, src/core/src/validator_registry_tp.rs
=> Add validator registry tp and deps

src/core/src/engine.rs
Add c-test and z-test to engine.rs. Parts stubbed out for validator
registry in c-test. z-test only placeholder as tightly coupled with
validator registry.
=> Integrate c-test and z-test to core

src/core/src/validator_registry_view.rs
=> validator registry view complete

demo.yaml, poet2-engine.dockerfile, poet2-validator.dockerfile
Build time improved by 60% to 20-30 mins from an earlier 1-2 hrs
Build stability and synchronous startup improved significantly
=> Multi-validator build improvements

poet2-validator.dockerfile
=> Removed unecessary deps in validator dockerfile

demo.yaml, src/core/src/consensus_state.rs, src/core/src/enclave_sim.rs, src/core/src/engine.rs, src/core/src/main.rs, src/core/src/poet2_util.rs, src/core/src/service.rs
=> Refactored code updates and optimizations

src/core/src/service.rs
=> wait_time calc improved

src/core/src/enclave_sim.rs, src/core/src/engine.rs, src/core/src/service.rs
=> Fix wait_certificate workflow bugs

demo3.yaml, demo5.yaml, src/core/src/consensus_state.rs, src/core/src/consensus_state_store.rs, src/core/src/engine.rs, src/core/src/service.rs
Fix multiple bugs in fork resolution work flow. Merge changes from master.
=> Bug fixes and stabilization for fork resolution

src/core/src/engine.rs, src/core/src/main.rs, src/core/src/service.rs, src/core/src/settings_view.rs
=> Add poet2 settings view struct for settings IO

demo3.yaml, src/core/src/engine.rs
Remove stubbed parts from c-test and make it runable.
Signed-off-by: Shourya Anand <shouryax.anand@intel.com>
=> Enable c-test

demo-sgx.yaml, demo5.yaml, src/core/src/engine.rs
Address poet2_util refactor in C-test enabling. Add
C-test setting to multi-validator compose files.
Signed-off-by: Rajeev Ranjan <rajeev2.ranjan@intel.com>
=> Fix merge bugs

src/core/Cargo.toml, src/core/src/engine.rs
Update method signature for engine's start method.
Signed-off-by: Rajeev Ranjan <rajeev2.ranjan@intel.com>
=> Fix for sdk changes

.env, Jenkinsfile, copy-debs.yaml, docker-compose-installed.yaml, packaging/systemd/poet2, packaging/systemd/poet2.service, src/core/Cargo.toml, src/core/Dockerfile-installed, src/core/src/enclave_sgx.rs
Signed-off-by: Pankaj Goyal <pankaj.goyal@intel.com>
=> PoET2 debian creation and Jenkinsfile addition

src/core/src/check_consensus.rs, src/core/src/engine.rs, src/core/src/main.rs
=> Poet engine modularization

src/core/src/engine.rs
=> Fix library dependencies order
